"""Local LLM backend using Ollama's structured-output API.

An LLM does not have a measurable graph path like WordNet, so its distances
are calibrated judgements. The prompt defines the scale and ``--explain``
keeps each short rationale beside the generated term for review.
"""

from __future__ import annotations

import json
from copy import deepcopy
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from .cluster import BackendError, Term, normalise

DEFAULT_URL = "http://localhost:11434/api/generate"
DEFAULT_TIMEOUT = 90.0
# This is an output transport size, not a semantic target. More batches are
# requested only while the model finds novel terms under the chosen threshold.
BATCH_SIZE = 12
DEFAULT_MAX_VARIANTS = 250

_SCHEMA = {
    "type": "object",
    "properties": {
        "variants": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "term": {"type": "string"},
                    "relation": {
                        "type": "string",
                        "enum": ["equivalent", "narrower", "associated", "broader", "contextual"],
                    },
                    "reason": {"type": "string", "maxLength": 120},
                },
                "required": ["term", "relation", "reason"],
                "additionalProperties": False,
            },
        },
        "complete": {"type": "boolean"},
    },
    "required": ["variants", "complete"],
    "additionalProperties": False,
}

_DISTANCE = {
    "equivalent": 0.15,
    "narrower": 0.25,
    "associated": 0.35,
    "broader": 0.40,
    "contextual": 0.50,
}
_RELATIONS = tuple(_DISTANCE)


class LLMBackend:
    """Semantic variants generated by a locally running Ollama model."""

    name = "llm"

    def __init__(
        self,
        model: str,
        *,
        url: str = DEFAULT_URL,
        timeout: float = DEFAULT_TIMEOUT,
        max_variants: int = DEFAULT_MAX_VARIANTS,
    ) -> None:
        if not model:
            raise BackendError(
                "--backend llm needs a local model name",
                remedy="pass --llm-model MODEL or set CLUSTERGREP_LLM_MODEL",
            )
        if timeout <= 0:
            raise BackendError("--llm-timeout must be greater than zero")
        if max_variants < 1:
            raise BackendError("--llm-max-variants must be at least one")
        self.model = model
        self.url = url
        self.timeout = timeout
        self.max_variants = max_variants

    def expand(self, word: str, threshold: float) -> Iterable[Term]:
        seen = {normalise(word)}
        while len(seen) - 1 < self.max_variants:
            remaining = self.max_variants - (len(seen) - 1)
            batch_size = min(BATCH_SIZE, remaining)
            payload = {
                "model": self.model,
                "prompt": _prompt(word, _RELATIONS, seen, batch_size),
                "format": _schema(batch_size),
                "stream": False,
                # This bounds one transport batch, not the cluster's size.
                "options": {"temperature": 0, "num_predict": 24 * batch_size + 24},
            }
            response = self._request(payload)
            variants, complete = _variants(response, seen, batch_size, _RELATIONS)
            if not variants:
                return
            yield from variants
            if complete:
                return

    def _request(self, payload: dict) -> object:
        body = json.dumps(payload).encode("utf-8")
        request = Request(
            self.url,
            data=body,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urlopen(request, timeout=self.timeout) as response:
                data = json.load(response)
        except (HTTPError, URLError, TimeoutError, OSError) as exc:
            raise BackendError(
                f"could not reach local LLM at {self.url}: {exc}",
                remedy="start Ollama, then retry; e.g. ollama serve",
            ) from exc
        except json.JSONDecodeError as exc:
            raise BackendError("local LLM returned invalid JSON") from exc

        if not isinstance(data, dict) or not isinstance(data.get("response"), str):
            raise BackendError("local LLM response did not contain a JSON result")
        try:
            return json.loads(data["response"])
        except json.JSONDecodeError as exc:
            raise BackendError("local LLM did not produce the requested JSON") from exc


def _prompt(
    word: str,
    allowed: tuple[str, ...],
    seen: set[str],
    batch_size: int,
) -> str:
    query = json.dumps(word)
    prior = ", ".join(sorted(seen))
    labels = ", ".join(allowed)
    return f"""Generate up to {batch_size} new English search terms related to {query}.
Return a coverage-saturated batch: add a term only if it covers a distinct meaning or
relationship not represented by the existing terms. Do not add spelling variants,
inflections, phrases that merely contain the query, or near-duplicate compounds.
Each item needs a term, one relation, and a reason of 12 words or fewer.
Allowed relation labels: {labels}. Existing terms: {prior}.
Set complete to true only when no further non-redundant terms in the allowed relation
classes remain; otherwise set it to false."""


def _schema(batch_size: int) -> dict:
    """Give Ollama an output bound as well as a JSON shape."""
    schema = deepcopy(_SCHEMA)
    schema["properties"]["variants"]["maxItems"] = batch_size
    return schema


def _variants(
    response: object,
    seen: set[str],
    batch_size: int,
    allowed: tuple[str, ...],
) -> tuple[list[Term], bool]:
    if (
        not isinstance(response, dict)
        or not isinstance(response.get("variants"), list)
        or not isinstance(response.get("complete"), bool)
    ):
        raise BackendError("local LLM result must contain variants and complete")

    terms: list[Term] = []
    for item in response["variants"][:batch_size]:
        if not isinstance(item, dict):
            continue
        text = item.get("term")
        relation = item.get("relation")
        reason = item.get("reason")
        if not isinstance(text, str) or relation not in allowed:
            continue
        text = normalise(text)
        if not text or len(text) > 120 or "\n" in text:
            continue
        if text in seen:
            continue
        seen.add(text)
        note = reason.strip().replace("\n", " ")[:160] if isinstance(reason, str) else ""
        via = f"LLM {relation}: {note}" if note else f"LLM {relation}"
        terms.append(Term(_DISTANCE[relation], text, via))
    return terms, response["complete"]
